# name: versch. Namen für schlecht/mittel/gut
# ingredients: material/anzahl
# cookingtime: Zeit in echtminuten die die zutaten kochen müssen
# distillruns: wie oft destilliert werden muss 0-10 (0=ohne Destillieren)
# wood: Holz des Fasses 0=alle Holzsorten 1=Birch 2=Oak 3=Jungle 4=Pine
# age: Zeit in Minecraft Tagen, die das getränk im fass reifen muss 0=kein reifen
# color: Farbe des Getränks nach destillieren/reifen
# difficulty: 1-10 genauigkeit der Einhaltung der Vorgaben
# alcohol: Alkoholgehalt 0-100 in Vol.% bei perfektem Getränk

#cooked: Auflistung ALLER möglichen Zutaten und die daraus entstehenden Tranknamen: (leer für undef.)

#words: Wörter und buchstaben die bei trunkenheit ersetzt werden sollen
#to: in welches wort es ersetzt werden soll
#pre: Wörter und Buchstaben vor dem gesuchten wort
#match: true = eines der "pre"-Wörter muss vor dem gesuchten Wort stehen,  false = keines der "pre" Wörter darf vor dem gesuchten stehen
#alcohol: 1-100 trunkenheit ab der die wörter ersetzt werden
#percentage: Wahrscheinlichkeit des Ersetzen eines wortes in prozent


recipes:
   1:
      name: Ranziges Weißbier/Weißbier/Feines Weißbier
      ingredients: 
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Ranziges Bier/Bier/Feines Bier
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Ranziges Dunkelbier/Dunkelbier/Feines Dunkelbier
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Scheußlicher Met/Met/Goldener Met
      ingredients: 
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 10
   5:
      name: Apfelmet/Süßer Apfelmet/Goldensüßer Apfelmet
      ingredients: 
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      COLOR: ORANGE
      difficulty: 4
      alcohol: 12
   6:
      name: Rum/Goldener Rum/Perfekter Rum
      ingredients: 
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 60
   7:
      name: Kartoffelsuppe
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
cooked:
   WHEAT: Getreideferment
   SUGAR_CANE: Zuckersud
   APPLE: Apfelmost
   POTATO_ITEM: Kartoffelmaische
   LONG_GRASS: Kräuterbrühe
words:
   ch:
      to: sch
      pre: u,s,o,a
      match: false
      alcohol: 20
      percentage: 70
   h:
      to: hh
      percentage: 60
   u:
      to: uuh
      percentage: 20
   das:
      to: dass
      percentage: 10
      alcohol: 40