# name: versch. Namen für schlecht/mittel/gut
# ingredients: material/Anzahl
# cookingtime: Zeit in Echtminuten die die Zutaten kochen müssen
# distillruns: Wie oft destilliert werden muss 0-10 (0=ohne Destillieren)
# wood: Holz des Fasses 0=alle Holzsorten 1=Birch 2=Oak 3=Jungle 4=Pine
# age: Zeit in Minecraft-Tagen, die das Getränk im Fass reifen muss 0= kein reifen
# color: Farbe des Getränks nach destillieren/reifen
# difficulty: 1-10 Genauigkeit der Einhaltung der Vorgaben (1 = ungenau/einfach 10 = sehr genau/schwer)
# alcohol: Alkoholgehalt 0-100 in Vol.% bei perfektem Getränk

#cooked: Auflistung ALLER möglichen Zutaten und die daraus entstehenden Tranknamen: (leer für undef.)

#words: Wörter und Buchstaben die bei Trunkenheit ersetzt werden sollen (besondere: -start = an den anfang, -end = ans ende, -random = zufällige position, -space anstatt leerzeichen)
#to: in welches wort es ersetzt werden soll
#pre: Wörter und Buchstaben vor dem gesuchten wort
#match: true = eines der "pre"-Wörter muss vor dem gesuchten Wort stehen,  false = keines der "pre" Wörter darf vor dem gesuchten stehen
#alcohol: 1-100 trunkenheit ab der die Wörter ersetzt werden
#percentage: Wahrscheinlichkeit des Ersetzen eines Wortes in Prozent


recipes:
   1:
      name: Ranziges Weißbier/Weißbier/Feines Weißbier
      ingredients: 
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Ranziges Bier/Bier/Feines Bier
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Ranziges Dunkelbier/Dunkelbier/Feines Dunkelbier
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Scheußlicher Met/Met/Goldener Met
      ingredients: 
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 10
   5:
      name: Apfelmet/Süßer Apfelmet/Goldensüßer Apfelmet
      ingredients: 
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      COLOR: ORANGE
      difficulty: 4
      alcohol: 12
   6:
      name: Rum/Goldener Rum/Perfekter Rum
      ingredients: 
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 60
   7:
      name: Abgeranzter Vodka/Vodka/Russischer Vodka
      ingredients: 
      - POTATO_ITEM/10
      cookingtime: 15
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 40
   8:
      name: minderwertiger Absinth/Absinth/Starker Absinth
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      color: GREEN
      difficulty: 8
   9:
      name: Kartoffelsuppe
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
cooked:
   WHEAT: Getreideferment
   SUGAR_CANE: Zuckersud
   APPLE: Apfelmost
   POTATO_ITEM: Kartoffelmaische
   LONG_GRASS: Kräuterbrühe
words:
   -  replace: ch
      to: sch
      pre: u,s,o,a
      match: false
      alcohol: 10
      percentage: 70

   -  replace: h
      to: hh
      pre: sch,h,t
      match: false
      percentage: 60
      alcohol: 20

   -  replace: u
      to: uuh
      percentage: 20

   -  replace: das
      to: dass
      percentage: 10
      alcohol: 40

   -  replace: '!'
      to: '!!'
      pre: '!'
      match: false
      percentage: 90

   -  replace: '!!'
      to: '!!!111!!einself!1!'
      pre: '!'
      match: false
      percentage: 20
      alcohol: 70

   -  replace: betrunken
      to: brhetriunkhn
      pre: bist,seid
      match: false
      percentage: 70
      alcohol: 65

   -  replace: laufen
      to: lnhfeeehn
      pre: kannst,kannst noch,kannst nicht
      match: false
      percentage: 80
      alcohol: 85

   -  replace: gehen
      to: hgheehn
      pre: kannst,kannst noch,kannst nicht
      match: false
      percentage: 80
      alcohol: 85

   -  replace: -space
      to: ''
      pre: h,g,w
      match: true
      alcohol: 10

   -  replace: -space
      to: ''
      percentage: 50
      alcohol: 35

   -  replace: -space
      to: ''
      percentage: 10

   -  replace: -start
      to: dssho
      percentage: 20
      alcohol: 50

   -  replace: -start
      to: hhng
      percentage: 30
      alcohol: 50

   -  replace: -random
      to: lrg
      percentage: 10

   -  replace: -random
      to: lu
      percentage: 60
      alcohol: 40

   -  replace: -random
      to: blub
      percentage: 60
      alcohol: 70

   -  replace: -random
      to: lerg
      percentage: 40
      alcohol: 75

   -  replace: -random
      to: grulg
      percentage: 50
      alcohol: 80

   -  replace: -random
      to: ''
      percentage: 30

   -  replace: -random
      to: ''
      percentage: 50
      alcohol: 70

   -  replace: -end
      to: '!'
      percentage: 30
      alcohol: 30

   -  replace: -end
      to: ' *hicks*'
      percentage: 70
      alcohol: 30