name: Brewery
version: 1.2
main: com.dre.brewery.P
authors: [Milan Albrecht, Frank Baumann]
softdepend: [LWC]
commands:
  brewery:
    description: Command for Administration
    aliases: [brew,br]