name: Brewery
version: 1.0
main: com.dre.brewery.P
authors: [Milan Albrecht, Frank Baumann]
softdepend: [Vault]
commands:
  brewery:
    description: Command for Administration
    aliases: [brew,br]