name: 'Build and Publish to Hangar and Modrinth'

on:
  release:
    branches: [master]
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BreweryX
          path: |
            build/libs/BreweryX-*.jar
            !build/libs/BreweryX-*-original.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.release.prerelease }} == false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: BreweryX
          path: ./build/libs

      - name: Hangar publish
        uses: benwoo1110/hangar-upload-action@v1
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: 'BreweryX'
          version: ${{ github.event.release.tag_name }}
          channel: release
          description: ${{ github.event.release.body }}
          files: |
            [
              {
                "path": "./build/libs/BreweryX-*.jar",
                "platforms": ["PAPER", "FOLIA"]
              }
            ]
          platform_dependencies: |
            {
              "PAPER": ["1.13.x-1.21.x"],
              "FOLIA": ["1.18.x-1.21.x"]
            }

      - name: Modrinth publish
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: BreweryX
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            paper
            spigot
            bukkit
            folia
            purpur
          game-versions: |-
            1.13.x
            1.14.x
            1.15.x
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: ./build/libs/BreweryX-${{ github.event.release.tag_name }}.jar